{% set name = "jupyter_server_mathjax" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower|replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb1e6b6dc0686c1fe386a22b5886163db548893a99c2810c36399e9c4ca23943

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - jupyter-packaging >=0.7.9
    - nodejs
    - pip
  run:
    - python >=3.7
    - jupyter_server >=1.1,<3

test:
  requires:
    - pip
  imports:
    - jupyter_server_mathjax
  commands:
    - pip check
    - jupyter server extension list 2>&1 | grep -ie "jupyter_server_mathjax.*OK"

about:
  home: https://github.com/jupyter-server/jupyter_server_mathjax/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: MathJax resources as a Jupyter Server Extension.

extra:
  recipe-maintainers:
    - blink1073
    - fcollonval
